### ISSUE TITLE
CalligraphyFactory.OnViewCreatedInternal throws an InvalidCastException on Android 10

### ISSUE THREAD

**Issue by Ed-Hong** [nwestfall/Calligraphy.Xamarin#13]
After updating to the latest Nuget release with Android 10 support, one of the workflows in our app was experiencing a crash with the following stacktrace:

```  
ERROR : System.InvalidCastException: Specified cast is not valid.
at Calligraphy.Xamarin.CalligraphyFactory.OnViewCreatedInternal (Android.Views.View view, Android.Content.Context context, Android.Util.IAttributeSet attrs) [0x000db] in <636ad58454d34da899ec75f85f329bd1>:0
at Calligraphy.Xamarin.CalligraphyFactory.OnViewCreated (Android.Views.View view, Android.Content.Context context, Android.Util.IAttributeSet attrs) [0x00026] in <636ad58454d34da899ec75f85f329bd1>:0
at Calligraphy.Xamarin.CalligraphyLayoutInflater.OnCreateView (System.String name, Android.Util.IAttributeSet attrs) [0x0004d] in <636ad58454d34da899ec75f85f329bd1>:0
at Android.Views.LayoutInflater.n_OnCreateView_Ljava_lang_String_Landroid_util_AttributeSet_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_name, System.IntPtr native_attrs) [0x00017] in <7d2292394f8c488b97f5bc2a0ac0240d>:0 
at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.35(intptr,intptr,intptr,intptr)
```

I did some digging and found the culprit:
https://github.com/nwestfall/Calligraphy.Xamarin/blob/6d125bfac3dcf6fbe688c5607d10739b1d32f44a/Calligraphy.Xamarin/CalligraphyFactory.cs#L152-L153

In my case, we had some custom views of type `Android.Views.View` which it was trying to cast into a `Android.Support.V7.Widget.Toolbar`.

Because `IsAssignableFrom()` returns `true` when the current type is in the same hierarchy as the given type, a custom view of type `Android.Views.View` will pass the type check since `Android.Support.V7.Widget.Toolbar` inherits from `Android.Views.View`. I wasn't sure if there was a reason why the type check is being performed with `IsAssignableFrom()` specifically, since everywhere else in the function it just uses the `is` operator. 

Because of this, I've made two PRs which both fix this issue but in different ways: 
https://github.com/nwestfall/Calligraphy.Xamarin/pull/11
https://github.com/nwestfall/Calligraphy.Xamarin/pull/12

#11 changes the type checking implementation to just use the `is` operator and check it against the `Toolbar` type explicitly.
#12 is a more conservative fix which will just catch the exception if it's thrown, and then skip that view. This does not change the type checking implementation and still utilizes `IsAssignableFrom()` if that is to be preserved.

Whichever PR is more suitable is up to you and you're free to close the other 🙂

**Comment by nwestfall** [comment]
Thanks for the PR and the amazing find!

I wrote this library a while ago and I think I'm going to be in favor of #11  over #12 (mostly cause I just love `is` syntax 😄 ).  Let me review today and get one fo them merged in.

**Comment by Ed-Hong** [comment]
Awesome, thank you for the quick response and thank you for porting this library to Xamarin 👍 !

**Comment by nwestfall** [comment]
#11  has been merged and nuget.org is indexing the new package

https://www.nuget.org/packages/Calligraphy.Xamarin/1.0.20

Thanks for contribution!

**Comment by Ed-Hong** [comment]
Hey its me again,

It looks as though something went wrong with the 1.0.20 release - when I tried installing it and testing my workflow, I ran into the same `InvalidCastException` in the same spot, which seemed odd to me considering that #11 should have fixed that issue. Plus I'm not sure how it's throwing an `InvalidCastException` since there isn't a type cast taking place anymore in that function. 

When I loaded the project directly into my app and referenced it locally, I verified that it works. In addition, I also made sure to downgrade and upgrade the package from 1.0.19 back to 1.0.20 to make sure it wasn't using a cached assembly or anything. So the only thing I can point to is that it seems to be an issue with the nuget release.

Sorry, but would you be able to double check it?

Thanks in advance I really appreciate it 🙂

**Comment by nwestfall** [comment]
@Ed-Hong would you be able to provide a stack trace?  This will help me try to create a sample application with a custom view to try to reproduce.

**Comment by Ed-Hong** [comment]
The stack trace should be the same as the original, but I've reproduced it just now and pulled it fresh here:

```
  at Calligraphy.Xamarin.CalligraphyFactory.OnViewCreatedInternal (Android.Views.View view, Android.Content.Context context, Android.Util.IAttributeSet attrs) [0x000db] in <636ad58454d34da899ec75f85f329bd1>:0 
  at Calligraphy.Xamarin.CalligraphyFactory.OnViewCreated (Android.Views.View view, Android.Content.Context context, Android.Util.IAttributeSet attrs) [0x00026] in <636ad58454d34da899ec75f85f329bd1>:0 
  at Calligraphy.Xamarin.CalligraphyLayoutInflater.OnCreateView (System.String name, Android.Util.IAttributeSet attrs) [0x0004d] in <636ad58454d34da899ec75f85f329bd1>:0 
  at Android.Views.LayoutInflater.n_OnCreateView_Ljava_lang_String_Landroid_util_AttributeSet_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_name, System.IntPtr native_attrs) [0x00017] in <7d2292394f8c488b97f5bc2a0ac0240d>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.35(intptr,intptr,intptr,intptr)
```

**Comment by nwestfall** [comment]
Wow long day.... Ya I'll take a look, thank you.

**Comment by nwestfall** [comment]
I see you don't have line numbers in your stack trace, does this only happen in Release or with Obfuscation?

**Comment by Ed-Hong** [comment]
I'm assuming the no line numbers is due to me not having the symbols loaded for the dll, ie - it's the raw addresses

**Comment by Ed-Hong** [comment]
And that's correct I'm only experiencing the issue with the official Nuget release installed - I have not tried manually packaging it and installing however.

**Comment by nwestfall** [comment]
If you compile for `Debug` you don't get this?

**Comment by Ed-Hong** [comment]
Let me try that

**Comment by Ed-Hong** [comment]
Wow, yep

Just manually compiled and `nuget pack`'ed for `Debug`, installed the `.nupkg` locally, and it works

**Comment by Ed-Hong** [comment]
Also manually compiled and `nuget pack`'ed for `Release` - also works.

It really does look like it's just something up with the `.nupkg` on Nuget.org. 
I've been switching back and forth multiple times now and the ones that I compiled locally are working, but the one on Nuget.org looks as if it's not been updated somehow.

**Comment by nwestfall** [comment]
Interesting

If you revert back to the `.nupkg` on nuget.org, delete your `bin/obj` folders and retry does it work then?

**Comment by Ed-Hong** [comment]
Hey - sorry I'd gotten side tracked with other things and wasn't able to get back to you until now

Deleted the `bin` and `obj` folders, reverted back to the `.nupkg` on nuget.org, and still experiencing the crash.

**Comment by SimpsOff** [comment]
If it's any help: I had this issue because i was using an old binding of v2.3 Calligraphy, migrated to this (with the 1.0.20 release) and this fixed the exact same invalid cast issue i was having.

**Comment by Ed-Hong** [comment]
Hey sorry for the radio silence on this - I'd put off getting back to this issue until now, and I'm going to go ahead and close this issue.

It looks like something was wrong with my environment, though I still haven't entirely figured that one out yet. However, after testing on a different machine we were able to verify that the newest release fixes the issue.
