### ISSUE TITLE
Please update the code to support Android 10

### ISSUE THREAD

**Issue by omatrot** [nwestfall/Calligraphy.Xamarin#9]
https://github.com/InflationX/Calligraphy/issues/35#issuecomment-676523448

**Comment by nwestfall** [comment]
Merged the PR.  Thanks for contributing!

**Comment by nwestfall** [comment]
I think I just have to update the build scripts.  I'll work on this before closing this issue

**Comment by omatrot** [comment]
Sorry to bother you but My app is broken on Android 10 until you release a new version of the nuget. Do you think you'll be able to do it soon ?

**Comment by nwestfall** [comment]
Yes, my plan was to update the builds and get a version out this weekend.  Thanks for being patient.

**Comment by omatrot** [comment]
cool

**Comment by nwestfall** [comment]
@omatrot success!

https://ci.appveyor.com/project/nwestfall/calligraphy-xamarin/builds/35420128
https://www.nuget.org/packages/Calligraphy.Xamarin/

v0.1.19

Again, thank you for your patience and contribution!
